### ISSUE TITLE
Add guide on uploading data to NCBI SRA

### ISSUE THREAD

**Issue by mpinsky** [pinskylab/SRA-submission#1]
This might go in the cookbook, or perhaps it's long enough to be its own guide. It would cover how to upload de-multiplexed FASTQ files, BAM files, and de novo genomes to the NCBI SRA.

Some thoughts on steps (from a colleague who made https://www.ncbi.nlm.nih.gov/bioproject/PRJNA472166)
- First set up the Bioproject with details
- Then set up the Biosamples (batch submit via excel file)
- Then do SRA submission using metadata (template and .tab file attached)

The last step assuming the above is ok is to upload files by Aspera connect: https://www.ncbi.nlm.nih.gov/sra/docs/submitfiles/
-Install aspera connect first then add files using following command (e.g. in Terminal):
Aspera\ Connect.app/Contents/Resources/ascp -i aspera.openssh.txt -QT -l100m -k1 -d RAD_data_demultiplexed/SRA_submission/ subasp@upload.ncbi.nlm.nih.gov:uploads/name@email.com_zREFMzyh
check for no empty or corrupted files (this will be automatically generated once you try and auto complete)

Related files:
[SRA_metadata_acc.txt](https://github.com/pinskylab/pinskylab_methods/files/4103223/SRA_metadata_acc.txt)
[SRA_metadata_acc.xlsx](https://github.com/pinskylab/pinskylab_methods/files/4103224/SRA_metadata_acc.xlsx)
[BIOSAMPLES_CB_Model.organism.animal.1.0.xlsx](https://github.com/pinskylab/pinskylab_methods/files/4103225/BIOSAMPLES_CB_Model.organism.animal.1.0.xlsx)

**Comment by mstuart1** [comment]
Transferred issue to SRA repo.  Apparently closing it in one spot closes it in the other...

**Comment by jahoey** [comment]
fixed with commit a9bf047d7e640a2fee85a121727da188c7d75c9e

**Comment by jahoey** [comment]
If we want this to go somewhere else, let me know. I do link to some of the files from this repository as examples of the BioSamples and SRA metadata files that need to be uploaded to NCBI

**Comment by mpinsky** [comment]
If this guide seems good to you, @jahoey , you can go ahead and close the issue. @mstuart1 Is this all linked from the genomics repo and/or the cookbook?

**Comment by jahoey** [comment]
I have linked the NCBI guide to pinskylab_methods. @mstuart1 I think only you have the ability to make this repo public at the moment.

**Comment by mstuart1** [comment]
It is now public.
